# Generated by Django 2.2.3 on 2019-07-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200)),
                ('profileimage', models.CharField(max_length=300)),
                ('account', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
