# Generated by Django 2.2.3 on 2019-08-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_login', '0002_auto_20190727_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profileimage',
            field=models.CharField(max_length=200),
        ),
    ]
