# Generated by Django 2.2.3 on 2019-08-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_login', '0003_auto_20190804_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='nickname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
