# Generated by Django 2.2.3 on 2019-08-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_login', '0004_auto_20190804_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='account',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
