# Generated by Django 2.2.3 on 2019-08-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_login', '0006_auto_20190805_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='nickname',
            field=models.CharField(max_length=200),
        ),
    ]
