# Generated by Django 2.2.3 on 2019-08-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_login', '0007_auto_20190805_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='account',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='profileimage',
            field=models.CharField(max_length=200),
        ),
    ]
