# Generated by Django 2.2.3 on 2019-08-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_login', '0008_auto_20190805_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='kakao_Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200)),
                ('account', models.CharField(max_length=200)),
                ('profileimage', models.CharField(max_length=200)),
                ('platfrom', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
