# Generated by Django 2.2.3 on 2019-08-08 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_login', '0009_auto_20190809_0447'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='kakao_Users',
            new_name='Users',
        ),
    ]
